name: 'Trigger monorepo workflow'

on:
  push:
    branches:
      - '*'

jobs:
  trigger_monorepo_workflow:
    name: 'Trigger monorepo workflow'
    uses: gw2auth/gw2auth.com-monorepo/.github/workflows/trigger_monorepo_workflow.yml@beta
    secrets:
      token: ${{ secrets.MONOREPO_DISPATCH_PAT }}